FROM golang:1.22

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . /app

RUN CGO_ENABLED=0 GOOS=linux go build -o merchantSearchApp cmd/merchant_search/main.go

EXPOSE 6000

# Run
CMD ["/app/merchantSearchApp"]